#!/usr/bin/env python3
"""Generate Word / PowerPoint / Markdown deliverables from the populated workbook.

Reads the workbook (source of truth), filters by class, and writes deliverables.
Runs only after qa-validator passes (the orchestrator enforces ordering;
this script also refuses to run if hooks/.qa_state is not 'pass').
"""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path

try:
    from openpyxl import load_workbook
except ImportError:
    sys.exit("ERROR: openpyxl not installed. Run: python3 -m pip install --user openpyxl")

QA_STATE = Path(__file__).resolve().parent.parent / "hooks" / ".qa_state"


def _require_qa_pass():
    if not QA_STATE.exists() or not QA_STATE.read_text().startswith("pass "):
        sys.exit("REFUSED: qa-validator has not logged a pass. Run workbook.py qa first.")


def _read(path: Path) -> dict:
    wb = load_workbook(path)
    def rows(sheet):
        return [r for r in wb[sheet].iter_rows(min_row=2, values_only=True) if r and any(c not in (None, "") for c in r)]
    return {
        "guide":  rows("Guide"),
        "am":     rows("Assumption Matrix"),
        "mvp":    rows("MVP Specifications"),
        "scope":  rows("Scoping Matrix"),
        "ev":     rows("Evidence Log"),
        "oq":     rows("Open Questions"),
    }


def _slug(path: Path) -> str:
    return path.stem


def export_md(data, out_dir: Path, slug: str) -> Path:
    md = []
    md.append(f"# {slug} — Product Brief\n")
    md.append("## MVP Scope (STRONG signals only)\n")
    for r in data["mvp"]:
        md.append(f"- **{r[1]}** — {r[2]}  _(assumptions: {r[3]})_")
    md.append("\n## Use-Case Priorities\n")
    for r in data["scope"]:
        md.append(f"- `{r[0]}` ({r[2]}) — {r[1]}  _(assumptions: {r[3]})_")
    md.append("\n## Open Questions (CONTESTED)\n")
    for r in data["oq"]:
        md.append(f"- {r[1]}  _why: {r[2]}_")
    md.append("\n## Assumption Matrix\n")
    md.append("| id | class | score | text |")
    md.append("|---|---|---|---|")
    for r in data["am"]:
        md.append(f"| {r[0]} | {r[4]} | {r[3]} | {r[1]} |")
    md.append("\n## Evidence Appendix\n")
    for r in data["ev"]:
        if r[3] == "no-signal":
            continue
        md.append(f"- [{r[1]} @ {r[3]}] ({r[4]:+}) \"{r[2]}\"")
    out = out_dir / f"{slug}.md"
    out.write_text("\n".join(md) + "\n")
    return out


def export_word(data, out_dir: Path, slug: str) -> Path:
    try:
        from docx import Document
    except ImportError:
        sys.exit("ERROR: python-docx not installed. Run: python3 -m pip install --user python-docx")
    doc = Document()
    doc.add_heading(f"{slug} — Product Brief", level=1)

    doc.add_heading("MVP Scope (STRONG signals only)", level=2)
    for r in data["mvp"]:
        p = doc.add_paragraph(style="List Bullet")
        p.add_run(f"{r[1]} — ").bold = True
        p.add_run(f"{r[2]}  (assumptions: {r[3]})")

    doc.add_heading("Use-Case Priorities", level=2)
    for r in data["scope"]:
        doc.add_paragraph(f"{r[0]} ({r[2]}) — {r[1]}  (assumptions: {r[3]})", style="List Bullet")

    doc.add_heading("Open Questions (CONTESTED)", level=2)
    for r in data["oq"]:
        doc.add_paragraph(f"{r[1]} — why: {r[2]}", style="List Bullet")

    doc.add_heading("Assumption Matrix", level=2)
    table = doc.add_table(rows=1, cols=4)
    hdr = table.rows[0].cells
    hdr[0].text, hdr[1].text, hdr[2].text, hdr[3].text = "id", "class", "score", "text"
    for r in data["am"]:
        c = table.add_row().cells
        c[0].text, c[1].text, c[2].text, c[3].text = str(r[0]), str(r[4]), str(r[3]), str(r[1])

    doc.add_heading("Evidence Appendix", level=2)
    for r in data["ev"]:
        if r[3] == "no-signal":
            continue
        doc.add_paragraph(f"[{r[1]} @ {r[3]}] ({r[4]:+}) \"{r[2]}\"", style="List Bullet")

    out = out_dir / f"{slug}.docx"
    doc.save(out)
    return out


def export_ppt(data, out_dir: Path, slug: str) -> Path:
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
    except ImportError:
        sys.exit("ERROR: python-pptx not installed. Run: python3 -m pip install --user python-pptx")
    prs = Presentation()
    blank = prs.slide_layouts[5]  # title only

    def slide(title, bullets):
        s = prs.slides.add_slide(blank)
        s.shapes.title.text = title
        tb = s.shapes.add_textbox(Inches(0.5), Inches(1.3), Inches(9), Inches(5.5)).text_frame
        tb.word_wrap = True
        for i, b in enumerate(bullets):
            p = tb.paragraphs[0] if i == 0 else tb.add_paragraph()
            p.text = b
            p.font.size = Pt(16)

    counts = {"STRONG": 0, "CONTESTED": 0, "WEAK": 0, "INVALIDATED": 0}
    for r in data["am"]:
        counts[r[4]] = counts.get(r[4], 0) + 1

    slide(f"{slug}", ["Customer interview readout", "Generated by Smart Interview"])
    slide("Scoring summary", [f"{k}: {v}" for k, v in counts.items()])
    slide("MVP scope (STRONG only)", [f"{r[1]} — {r[2]}" for r in data["mvp"]] or ["(none yet)"])
    slide("Use-case priorities", [f"{r[0]} ({r[2]}) — {r[1]}" for r in data["scope"]] or ["(none yet)"])
    slide("Open questions (CONTESTED)", [f"{r[1]}  [{r[2]}]" for r in data["oq"]] or ["(none)"])
    top_ev = [r for r in data["ev"] if r[3] != "no-signal"][:8]
    slide("Top evidence", [f'[{r[1]} {r[4]:+}] "{r[2]}"' for r in top_ev] or ["(no signals)"])
    slide("Next steps", ["Validate CONTESTED via follow-up interviews", "Lock MVP scope", "Draft PRD"])

    out = out_dir / f"{slug}.pptx"
    prs.save(out)
    return out


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--path", required=True)
    p.add_argument("--format", required=True, choices=["word", "ppt", "md", "all"])
    p.add_argument("--out", default="output")
    args = p.parse_args()

    _require_qa_pass()
    path = Path(args.path)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    data = _read(path)
    slug = _slug(path)

    generated = []
    fmts = [args.format] if args.format != "all" else ["md", "word", "ppt"]
    for f in fmts:
        if f == "md":   generated.append(str(export_md(data, out_dir, slug)))
        if f == "word": generated.append(str(export_word(data, out_dir, slug)))
        if f == "ppt":  generated.append(str(export_ppt(data, out_dir, slug)))

    print(json.dumps({"generated": generated}))


if __name__ == "__main__":
    main()
